#!/bin/bash

# initiations {{{
BASHRC_INTERACTIVE_MODE_INIT=1
. ~/.bashrc # source .bashrc to load my git aliases
shopt -s expand_aliases # needed for the git aliases to work properly
# }}}

# vars {{{

command=""

# options {{{
option_project_readable_name=""
# }}}

# arguments {{{
user_project_name_github="" # $1
path="" # $2
# }}}

# data {{{

# project submodules {{{

valid_commands=( new update update-skeleton update-submodules )

submodules=(
   #"repository" "path" "readonly"
    "theosp/theosp_common_build_tools" "build" 0
    "theosp/theosp_common_js" "javascript/src/theosp_common_js" 0
    "theosp/theosp_common_css" "style/src/theosp_common_css" 0
    "theosp/headjs" "javascript/src/headjs" 0
)

submodules_names=()
n=${#submodules[*]}
for (( i=0; i < n; i += 3 )); do
    submodules_names+=( "${submodules[i]}" )
done
unset i n
submodules_names_string=${submodules_names[@]}
# }}}

# }}}

# }}}

# functions {{{

# show_help () {{{
show_help () {
    cat <<EOF
NAME
    theosp-projects - Initiate/Update web application projects

SYNOPSIS
    ./theosp-projects COMMAND [--project-readable-name readable_name] [--] <github-rep> [<path>]
    ./theosp-projects [-h] [--help]

OPTIONS

COMMANDS
    new
        new theosp project

    update
        update theosp project's skeleton and submodules

    update-skeleton
        update theosp project's skeleton

    update-submodules
        update theosp project's submodules
EOF
}
# }}}

# submodule {{{

# submodule_install (repository_path) {{{
submodule_install () {
    local path="$1"

    pushd . > /dev/null
    cd "$path"

    local i n=${#submodules[*]}
    for (( i=0; i < n; i += 3 )); do
        gsmag "${submodules[i]}" "${submodules[$((i + 1))]}" ${submodules[$((i + 2))]}
    done

    pwd
    gsmir

    popd > /dev/null
}
# }}}

# submodule_update (repository_path) {{{
submodule_update () {
    local path="$1"

    pushd . > /dev/null

    cd "$path"

    popd > /dev/null
}
# }}}

# }}}

# recursive_find_replace (path, search, replace) {{{
recursive_find_replace () {
    local path="$1"
    local search="$2"
    local replace="$3"

    find "$path" -type f -exec sed -i "s/$search/$replace/g" {} \;
}
# }}}

# commands {{{

# command_new (github_project, path) {{{
command_new () {
    local github_project="$1"
    local path="$2"

    # init {{{
    gig "$github_project" "$path"
    # }}}

    # add skeleton files {{{
    command_update_skeleton "$github_project" "$path"

    pushd . > /dev/null
    cd "$path"

    ga .

    gcm "Add project base"

    popd > /dev/null
    # }}}
    
    # install submodules {{{
    submodule_install "$path"

    pushd . > /dev/null
    cd "$path"

    ga .

    gcm "Add submodules: $submodules_names_string"

    popd > /dev/null
    # }}}

    # tag and push tag {{{
    pushd . > /dev/null
    cd "$path"

    gta "project_skeleton"

    ghto

    popd > /dev/null
    # }}}
    
    # make {{{
    pushd . > /dev/null
    cd "$path"

    make

    ga .

    gcm "make"

    popd > /dev/null
    # }}}

    # push {{{
    pushd . > /dev/null
    cd "$path"

    ghoc

    popd > /dev/null
    # }}}
}
# }}}

# command_update_skeleton (github_project, path) {{{
command_update_skeleton () {
    local github_project="$1"
    local path="$2"
    local project_readable_name="${option_project_readable_name:-${github_project#*/}}"

    cp -r skeleton/* "$path"

    recursive_find_replace "$path" "|project_readable_name|" "$project_readable_name"
}
# }}}

# }}}

# }}}

# parse argv {{{

# load command {{{
if (($# > 0)); then
    command="$1"
    shift
else
    show_help
    exit 1
fi

valid_command=0
n=${#valid_commands[*]}
for (( i=0; i < n; i += 1 )); do
    item="${valid_commands[i]}"

    if [[ "$item" == "$command" ]]; then
        valid_command=1
    fi
done

if (( $valid_command == 0 )); then
    echo "theosp-projects: '$command' is not a theosp-projects command." 1>&2
    show_help

    exit 1
fi

unset i n item valid_command
# }}}

# load options {{{
# original: http://mywiki.wooledge.org/BashFAQ/035 (Manual Loop)
while [[ $1 == -* ]]; do
    case "$1" in
      -h|--help|-\?)
          show_help
          exit 0
      ;;
      --project-readable-name)
          if (($# > 1)); then
              option_project_readable_name="$2"
              shift 2
          else
              echo "--project-readable-name requires an argument" 1>&2
              exit 1
          fi
      ;;
      --)
          shift
          break
      ;;
      -*)
          echo "invalid option: $1" 1>&2
          show_help
          exit 1
      ;;
    esac
done
# }}}

# load arguments {{{
if (($# > 0)); then
    user_project_name_github="$1"

    path="${2:-${user_project_name_github#*/}}"
else 
    echo "Please provide the github repository" 1>&2
    show_help

    exit 1
fi
# }}}

# }}}

# call command {{{
command_"${command/-/_}" "$user_project_name_github" "$path"
# }}}

# vim:ft=bash:fdm=marker:fmr={{{,}}}:
